// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScentShop.Models;

namespace ScentShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210416193832_RebuildingSeedFile4")]
    partial class RebuildingSeedFile4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ScentShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "For Her"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "For Him"
                        });
                });

            modelBuilder.Entity("ScentShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ScentShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PerfumeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ScentShop.Models.Perfume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerfumeOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("KeyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Perfumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Chance is a fragrance created like a constellation, a composition like an olfactory sphere that opens up in an infinite movement. At the heart of this sphere is a sensuous balance warmed by Vanilla, with pronounced Jasmine Absolute and Iris. A mysterious alchemy, heightened by the intensity of White Musk.",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Jasmine, Pink Pepper, Vanilla",
                            Name = "Chance",
                            Price = 108m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "With its unprecedented use of aldehydes, which add layers of complexity, N°5 was the world’s first abstract fragrance. The Eau de Parfum draws inspiration from the Parfum with which it shares its floral aldehyde signature. This floral bouquet composed around May Rose and Jasmine features bright citrus top notes. Aldehydes create a unique presence while the smooth touch of Bourbon Vanilla leaves an incredibly sensual trail.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Aldehydes, Jasmine, Sandalwood",
                            Name = "N°5",
                            Price = 108m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dior",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "This fragrance opens with the exotic, floral-fruity notes of ylang ylang, while Damascus rose, and both Grasse jasmine and Indian jasmine sambac exude a seductive warmth. This scent is the ultimate expression of femininity and luxury and is floral yet mysterious, a confident signature to celebrate your feminine allure.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Ylang Ylang, Damascus Rose, Jasmine",
                            Name = "J'adore",
                            Price = 135m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "This eau de parfum is a floral declaration of love. In the heart of the perfume, the fresh, sensual beauty of the Grasse rose combines with the boldness of Damascus rose. They are woven with Calabrian bergamot, vivid rosewood from French Guiana, and pink pepper from Réunion Island.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Grasse Rose, Bergamot, Rosewood",
                            Name = "Miss Dior",
                            Price = 105m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Gucci",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "A sumptuous white floral Gorgeous Gardenia is Gucci’s faithful creation of the perfect gardenia. The Gorgeous Gardenia woman exudes a sultry sensuality that is lushly enticing. Men are drawn to her as bees are to a blossoming flower.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Red Berries, Pear, White Gardenia",
                            Name = "Flora",
                            Price = 85m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Gucci",
                            Capacity = 47,
                            CategoryId = 1,
                            Description = "This fragrance contains notes of sparkling Mediterranean citruses that radiate from the top, while the perfume‘s feminine white floral heart is illuminated with dewy petals underscored with the lasting signature notes of the original essence. It is a fresh and bright scent that unfolds with a sheer sensuality.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Casablanca Lily, Sandalwood",
                            Name = "Bamboo",
                            Price = 89m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Lancôme",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Made with the most precious natural ingredients, expressing notes of iris, patchouli, praline, and vanilla, this feminine, complex scent is the modern interpretation of an oriental fragrance with a twist of gourmand.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Iris, Vanilla, Praline",
                            Name = "La Vie Est Belle",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Michael Kors",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Michael Kors Wonderlust is an oriental gourmand fragrance that captures an infinite desire for discovery. A blend of luxurious blossoms mingled with delectably spiced notes charts a course to far-off destinations, instantly transporting you with each ingredient.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Almond Cream, Dianthus",
                            Name = "Wonderlust",
                            Price = 120m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Jo Malone London",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Built on a platform of rich amber, this contrasting fragrance is subtly woven with the clean smell of barber's soap. With top notes that evoke a natural, classic cologne - a rich blend of fresh mandarin, bergamot, and cardamom that melds into the sensual mid notes of patchouli, tonka bean, and vanilla; and finishes with the clean, leathery notes of vetiver, neroli, orange blossom, saffron, and suede, Amber Pour Homme is a fragrance for the self-assured man.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Almond Cream, Dianthus",
                            Name = "Wood Sage & Sea Salt",
                            Price = 149m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Neroli",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "This long-lasting eau de parfum centers around timeless orange flower and neroli mixed with a hint of pink pepper. Playful and feminine tones inspired by the flowers of Grasse are complemented by an airy and soft layer of honey and musk, which wraps you with a second-skin effect.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Neroli, Orange Flower, Pink Pepper",
                            Name = "Rag & Bone",
                            Price = 150m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Ralph Lauren",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Sparkling notes of pink pepper and mandarin orange effervesce into a fantasy of rose and jasmine, finding a fairy tale ending in the sensual embrace of woody musk and patchouli.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Lily, White Floral",
                            Name = "Romance",
                            Price = 178m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "This perfume is lavished with shimmering freshness, honey, rum, and a dramatic floral veil, and it lives in Black Orchid’s world of glamorous mystique, while exuding its own ultra-feminine essence.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Orange Blossom, Hyacinth, Jonquil",
                            Name = "Velvet Orchid",
                            Price = 134m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Calvin Klein",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "The composition opens with fresh citrus and green notes, that is followed by the note of violet and lily-of-the-valley. The note of carnation with its spiciness gives the floral heart slightly peppery accord. The final notes are gentle with powdery heliotrope, pink sandalwood and transparent musky notes.",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Citrus, Lily, Pink Sandalwood",
                            Name = "Eternity",
                            Price = 155m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Giorgio Armani",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "A sweet take on a floral fragrance, this women's perfume opens with luminous notes of blackcurrant nectar and mandarin. Orange blossom forms the heart of the fragrance and warm vanilla anchors the irresistible blend for a lasting scent.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Citrus, Lily, Pink Sandalwood",
                            Name = "Si",
                            Price = 98m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "In this new olfactive journey, ylang-ylang is amplified while rum absolute and black plum become even more pronounced, augmenting the sensuality of TOM FORD‘s original perfume, Black Orchid Eau de Parfum.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Black Truffle, Black Orchid, Patchouli",
                            Name = "Black Orchid",
                            Price = 134m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Dolce & Gabbana",
                            Capacity = 125,
                            CategoryId = 2,
                            Description = "The fragrance opens up with neroli and citrusy hints of mandarin and bergamot.At the heart is lavender.Touches of tobacco and tonka bean provide structure for the last dry notes of wood.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Sandalwood, Tonka Bean, Tobacco",
                            Name = "Pour Homme",
                            Price = 99m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "A woody, aromatic fragrance for the man who defies convention; a provocative blend of citrus and woods that liberates the senses. Fresh, clean, and profoundly sensual.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Citrus Accord, Labdanum, Sandalwood Cedar",
                            Name = "Bleu de Chanel",
                            Price = 80m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Dior",
                            Capacity = 60,
                            CategoryId = 2,
                            Description = "A radically fresh composition, Sauvage is both raw and noble. Radiant top notes burst with the juicy freshness of Calabrian bergamot, while amberwood unleashes a powerfully woody trail. Sauvage is a fragrance inspired by wide-open spaces under a blue sky that dominates a white-hot desert landscape.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Pepper, Amberwood",
                            Name = "Sauvage",
                            Price = 90m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The Dior Homme Eau de Toilette is an alluring combination of power and freshness. It is intensely woody and masculine, taking hold and leaving a lasting impression.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cedar, Haitian Vetiver, Patchouli Heart",
                            Name = "Homme",
                            Price = 120m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "Lucid and willful, Eau Sauvage is the perfume of the cult of elegance, refinement, and good humor. With the zest of citrus fruits for freshness, an invigorating bouquet of herbs, a hint of jasmine and vetiver for the sensual touch, and oakmoss to conquer and seduce, it will remain a fresh, discreet classic.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Lemon, Rosemary, Petit Grain",
                            Name = "Eau Sauvage",
                            Price = 95m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "A resolutely contemporary fragrance characterized by a meeting of extremes. Fresh, elegant notes blend in perfect harmony with bolder, more virile overtones to create a scent that is warm, subtle, and distinguished.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Hawthorne, Honeysuckle",
                            Name = "Fahrenheit",
                            Price = 77m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Dolce & Gabbana",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "Elegant and sensual, this perfume is decidedly modern and uniquely timeless all at once. The spicy fragrance features fresh top notes of grapefruit, coriander, and basil; a warm heart of cardamom and ginger; and a deep masculine base of tobacco, amber, and cedarwood.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cardamom, Cedarwood, Ginger, Tobacco",
                            Name = "The One For Men",
                            Price = 120m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Hermès",
                            Capacity = 55,
                            CategoryId = 2,
                            Description = "Terre d’Hermès is a symbolic narrative exploring raw material and its metamorphosis. A novel that expresses the alchemical power of the elements. An eau between earth and sky. A journey imbued with strength and poetry. Woody, vegetal, mineral.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Grapefruit Accord, Black Peppers, Flint",
                            Name = "Terre d’Hermès",
                            Price = 126m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Prada",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The perfumer Daniela Roche-Andrier created the composition in four basic accords : Amber – the main accord, rich and complex oriental base which includes amber, vanilla, labdanum, Tonka and patchouli; Fougere – or the aromatic accord with a remarkable soapy note, includes notes of pelargonium, vetiver, orange blossom and myrrh at the heart; Cologne – the refreshing citrusy top of bergamot, mandarin, neroli and cardamom; Leather – leather note is present at the base of the composition (leather, saffron and sandalwood).",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot Oil, Mandarin, Cardamom",
                            Name = "Amber",
                            Price = 94m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Ralph Lauren",
                            Capacity = 102,
                            CategoryId = 2,
                            Description = "The heart of the fragrance is aromatic cypress and clary sage which add another level of sophistication, freshness, and sensuality.  The scent peaks with the salty mineral Deep Ocean Accord that energizes and activates an even deeper level of freshness.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Hawaiian Green Mango, Cypress Oil",
                            Name = "Polo Deep Blue",
                            Price = 125m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Tom Ford",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "A composition of exotic, smoky woods including rare oud, sandalwood, rosewood, eastern spices, and sensual amber—revealing oud‘s rich and compelling power.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Rare Oud Wood, Chinese Pepper, Vanilla",
                            Name = "Oud Wood",
                            Price = 250m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "This perfume's rich blend of spicy heat and glowing citrus gives way to Indian kulfi, wrapped in rose absolute, jasmine accord, and orange flower. It also contains notes of extravagant amber with sandalwood and vanilla ember for a creamy, woody finish.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cardamom, Orange Flower, Sandalwood",
                            Name = "Noir Extreme",
                            Price = 180m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Versace",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "New and exquisite qualities of natural citrus, aquatic notes, and violet leaves combine with modern hints of fig leaf to give an incisive, Mediterranean freshness.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Aquatic Notes, Bergamot, Patchouli",
                            Name = "Dylan Blue",
                            Price = 200m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Versace",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "The new fragrance for men, Versace Pour Homme, blends essential ingredients of Mediterranean origin to hit aromatic notes.",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Bergamot, Neroli, Citron of Diamante",
                            Name = "Pour Homme",
                            Price = 200m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Nautica",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The composition opens with cold, green notes of leaves and apple. There is a tender dewy mimose in the heart, which is blended with watery note of lotus and an interesting accord of linen sail of a yacht. The composition is laid on a woody base, combined of cedar, moss, musk and amber.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Apple, Lotus, Cedar",
                            Name = "Voyage",
                            Price = 700m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Giorgio Armani",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "The fragrance for men is a scent of freedom, full of wind and water. The composition is built of a perfect harmony of sweet and salty notes of sea water and nuances of sunny warmth on your skin. Aqua di Gio is full of scorching Mediterranean sun. Bitter citrus with aromatic nuance of rosemary intertwines with salty, sea nuances and pellucid hedione. Sharp notes of spices are softened by woody base with warm, musky trail.",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Neroli, Green Tangerine",
                            Name = "Acqua di Gio",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("ScentShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PerfumeId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScentShop.Models.OrderDetail", b =>
                {
                    b.HasOne("ScentShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScentShop.Models.Perfume", "Perfume")
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("ScentShop.Models.Perfume", b =>
                {
                    b.HasOne("ScentShop.Models.Category", "Category")
                        .WithMany("Perfumes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScentShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("ScentShop.Models.Perfume", "Perfume")
                        .WithMany()
                        .HasForeignKey("PerfumeId");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("ScentShop.Models.Category", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("ScentShop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
