// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScentShop.Models;

namespace ScentShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210421134114_UpdatingSeedFile11")]
    partial class UpdatingSeedFile11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ScentShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "For Her"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "For Him"
                        });
                });

            modelBuilder.Entity("ScentShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ScentShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PerfumeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ScentShop.Models.Perfume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerfumeOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("KeyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Perfumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Chance is a fragrance created like a constellation, a composition like an olfactory sphere that opens up in an infinite movement. At the heart of this sphere is a sensuous balance warmed by Vanilla, with pronounced Jasmine Absolute and Iris. A mysterious alchemy, heightened by the intensity of White Musk.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861769/ScentShop/for%20Her/chanel-chance_opctto.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Jasmine, Pink Pepper, Vanilla, Iris",
                            Name = "Chance",
                            Price = 108m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "With its unprecedented use of aldehydes, which add layers of complexity, N°5 was the world’s first abstract fragrance. This floral bouquet composed around May Rose and Jasmine features bright citrus top notes. Aldehydes create a unique presence while the smooth touch of Bourbon Vanilla leaves an incredibly sensual trail.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861769/ScentShop/for%20Her/chanel-n5_nogmdh.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Aldehydes, Jasmine, Sandalwood",
                            Name = "N°5",
                            Price = 108m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dior",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "This fragrance opens with the exotic, floral-fruity notes of ylang ylang, while Damascus rose, and both Grasse jasmine and Indian jasmine sambac exude a warmth. This scent is the ultimate expression of femininity and luxury and is floral yet mysterious, a confident signature to celebrate the feminine allure.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1619012420/ScentShop/for%20Her/dior-jadore_eewtw5.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Ylang Ylang, Damascus Rose, Jasmine",
                            Name = "J'adore",
                            Price = 135m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "In the heart of this perfume, the fresh, sensual beauty of the Grasse rose combines with the boldness of Damascus rose. They are woven with Calabrian bergamot, vivid rosewood from French Guiana, and pink pepper from Réunion Island.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861769/ScentShop/for%20Her/dior-missdior_fpeatw.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Grasse Rose, Bergamot, Rosewood",
                            Name = "Miss Dior",
                            Price = 105m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Gucci",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Gucci Flora is the utterly feminine, deeply sensual fragrance for women inspired by Gucci's iconic Flora Pattern. The fragrance is characterized by contrasts and is for the classic, modern woman who has a youthful, feminine spirit.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861770/ScentShop/for%20Her/gucci-flora_p6gbdl.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Osmanthus, Peony, Rose",
                            Name = "Flora",
                            Price = 85m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Gucci",
                            Capacity = 47,
                            CategoryId = 1,
                            Description = "This fragrance contains notes of sparkling Mediterranean citruses that radiate from the top, while the perfume‘s feminine white floral heart is illuminated with dewy petals underscored with the lasting signature notes of the original essence. It is a fresh and bright scent that unfolds with a sheer sensuality.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861771/ScentShop/for%20Her/gucci-bamboo_sc4i5a.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Casablanca Lily, Sandalwood",
                            Name = "Bamboo",
                            Price = 89m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Lancôme",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Made with the most precious natural ingredients, expressing notes of iris, patchouli, praline, and vanilla, this feminine, complex scent is the modern interpretation of an oriental fragrance with a twist of gourmand.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861773/ScentShop/for%20Her/lancome-la-vie-est-belle_ihurwf.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Iris, Vanilla, Praline",
                            Name = "La Vie Est Belle",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Michael Kors",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Michael Kors Wonderlust is an oriental gourmand fragrance that captures an infinite desire for discovery. A blend of luxurious blossoms mingled with delectably spiced notes charts a course to far-off destinations, instantly transporting you with each ingredient.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861776/ScentShop/for%20Her/michael-kors-wonderlust_jvadod.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Almond Cream, Dianthus",
                            Name = "Wonderlust",
                            Price = 120m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Jo Malone London",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Escape the everyday along the windswept shore where white waves break and the air is fresh with sea salt and spray. Alive with the mineral scent of the rugged cliffs mingled with the woody earthiness of sage, this fragrance is lively, spirited, and totally joyful.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861773/ScentShop/for%20Her/jo-malone-wood-sage-sea-salt-cologne_syarnx.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Ambrette Seeds, Sea Salt, Sage",
                            Name = "Wood Sage",
                            Price = 149m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Neroli",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "This long-lasting eau de parfum centers around timeless orange flower and neroli mixed with a hint of pink pepper. Playful and feminine tones inspired by the flowers of Grasse are complemented by an airy and soft layer of honey and musk, which wraps you with a second-skin effect.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861773/ScentShop/for%20Her/rag-bone-neroli_vkneh5.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Neroli, Orange Flower, Pink Pepper",
                            Name = "Rag & Bone",
                            Price = 150m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Tom Ford",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Tom Ford reinvents classic tobacco with creamy tonka bean, vanilla, cocoa, dry fruit accords, and sweet wood sap for a modern, opulent, and heady impression of confidence.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861776/ScentShop/for%20Her/tom-ford-tobacco-vanille_xwtadn.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Tobacco Leaf, Ginger, Cocoa",
                            Name = "Tobacco Vanille",
                            Price = 340m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "This perfume is lavished with shimmering freshness, honey, rum, and a dramatic floral veil, and it lives in Black Orchid’s world of glamorous mystique, while exuding its own ultra-feminine essence.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618900528/ScentShop/for%20Her/tom-ford-velvet-orchid_my0mzu.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Orange Blossom, Hyacinth, Jonquil",
                            Name = "Velvet Orchid",
                            Price = 134m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Calvin Klein",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "The composition opens with fresh citrus and green notes, that is followed by the note of violet and lily-of-the-valley. The note of carnation with its spiciness gives the floral heart slightly peppery accord. The final notes are gentle with powdery heliotrope, pink sandalwood and transparent musky notes.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618862854/ScentShop/for%20Her/calvin-klein-eternity_nx42ln.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Citrus, Lily, Pink Sandalwood",
                            Name = "Eternity",
                            Price = 155m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Giorgio Armani",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "A sweet take on a floral scent. It opens with luminous notes of blackcurrant nectar and mandarin. Orange blossom forms the heart of the fragrance and warm vanilla anchors the irresistible blend for a lasting scent.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861773/ScentShop/for%20Her/giorgio-armani-si_mg396i.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Citrus, Lily, Pink Sandalwood",
                            Name = "Si",
                            Price = 98m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 1,
                            Description = "Black Orchid opens with aphrodisiacal black truffle and narcotic ylang ylang – touched with effervescent bergamot and bitter orange. Rum-soaked, sweet black plum surrounds the perfume‘s black orchid extract, while woody patchouli and creamy vanilla wrap the orchid in rich warmth.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618900532/ScentShop/for%20Her/tom-ford-black-orchid_izuvrm.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Black Truffle, Black Orchid, Patchouli",
                            Name = "Black Orchid",
                            Price = 134m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Dolce & Gabbana",
                            Capacity = 125,
                            CategoryId = 2,
                            Description = "The fragrance opens up with neroli and citrusy hints of mandarin and bergamot. At the heart is lavender. Touches of tobacco and tonka bean provide structure for the last dry notes of wood.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861787/ScentShop/for%20Him/dolcegabbana-por-homme_j9xht5.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Sandalwood, Tonka Bean, Tobacco",
                            Name = "Pour Homme",
                            Price = 99m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Chanel",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "A woody, aromatic fragrance for the man who defies convention. A provocative blend of citrus and woods that liberates the senses. Fresh, clean, and profoundly sensual.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861787/ScentShop/for%20Him/chanel-bleu-de-chanel_mhu9dp.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Citrus Accord, Labdanum, Sandalwood Cedar",
                            Name = "Bleu de Chanel",
                            Price = 80m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Dior",
                            Capacity = 60,
                            CategoryId = 2,
                            Description = "A radically fresh composition, Sauvage is both raw and noble. Radiant top notes burst with the juicy freshness of Calabrian bergamot, while amberwood unleashes a powerfully woody trail. Sauvage is a fragrance inspired by wide-open spaces under a blue sky that dominates a white-hot desert landscape.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861786/ScentShop/for%20Him/dior-sauvage_jvgijx.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Pepper, Amberwood",
                            Name = "Sauvage",
                            Price = 90m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The Dior Homme Eau de Toilette is an alluring combination of power and freshness. It is intensely woody and masculine, taking hold and leaving a lasting impression.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861787/ScentShop/for%20Him/dior-homme_ek0ni5.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cedar, Haitian Vetiver, Patchouli Heart",
                            Name = "Homme",
                            Price = 120m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "Eau Sauvage is the perfume of the cult of elegance, refinement, and good humor. With the zest of citrus fruits for freshness, an invigorating bouquet of herbs, and a hint of jasmine and vetiver, it will remain a fresh, discreet classic.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861788/ScentShop/for%20Him/dior-eau-sauvage_txzqlm.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Lemon, Rosemary, Petit Grain",
                            Name = "Eau Sauvage",
                            Price = 95m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Dior",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "A resolutely contemporary fragrance characterized by a meeting of extremes. Fresh, elegant notes blend in perfect harmony with bolder, more virile overtones to create a scent that is warm, subtle, and distinguished.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861786/ScentShop/for%20Him/dior-fahrenheit_farikl.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Hawthorne, Honeysuckle",
                            Name = "Fahrenheit",
                            Price = 77m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Dolce & Gabbana",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "Elegant and sensual, this perfume is decidedly modern and uniquely timeless all at once. The spicy fragrance features fresh top notes of grapefruit, coriander, and basil, warm heart of cardamom and ginger, and a deep masculine base of tobacco, amber, and cedarwood.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861789/ScentShop/for%20Him/dolcegabbana-the-one-for-men_vcv0qq.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cardamom, Cedarwood, Ginger, Tobacco",
                            Name = "The One For Men",
                            Price = 120m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Hermès",
                            Capacity = 55,
                            CategoryId = 2,
                            Description = "Terre d’Hermès is a symbolic narrative exploring raw material and its metamorphosis. A novel that expresses the alchemical power of the elements. An eau between earth and sky. A journey imbued with strength and poetry. Woody, vegetal, mineral.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861789/ScentShop/for%20Him/hermes-terre-dhermes_bchhfn.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Grapefruit Accord, Black Peppers, Flint",
                            Name = "Terre d’Hermès",
                            Price = 126m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Prada",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "With its highly natural charm, Prada makes and leaves a lasting impression. A rich, complex Amber intermingles with the clean, fresh scent of barber’s soap, typical of a fougère, and continues to evolve between a duet of olfactory contrasts.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861790/ScentShop/for%20Him/prada-amber_ypozz9.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot Oil, Mandarin, Cardamom, Neroli",
                            Name = "Amber",
                            Price = 94m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Ralph Lauren",
                            Capacity = 102,
                            CategoryId = 2,
                            Description = "The heart of the fragrance is aromatic cypress and clary sage which add another level of sophistication, freshness, and sensuality. The scent peaks with the salty mineral Deep Ocean Accord that energizes and activates an even deeper level of freshness.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861791/ScentShop/for%20Him/ralph-lauren-polo-deep-blue_ueo6b6.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Hawaiian Green Mango, Cypress Oil",
                            Name = "Polo Deep Blue",
                            Price = 125m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Tom Ford",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "A composition of exotic, smoky woods including rare oud, sandalwood, rosewood, eastern spices, and sensual amber — revealing oud‘s rich and compelling power.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861792/ScentShop/for%20Him/tom-ford-oud-wood_fhx3vn.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Rare Oud Wood, Chinese Pepper, Vanilla",
                            Name = "Oud Wood",
                            Price = 250m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Tom Ford",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "This perfume's rich blend of spicy heat and glowing citrus gives way to Indian kulfi, wrapped in rose absolute, jasmine accord, and orange flower. It also contains notes of extravagant amber with sandalwood and vanilla ember for a creamy, woody finish.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861791/ScentShop/for%20Him/tom-ford-noir-extreme_eohhlm.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Cardamom, Orange Flower, Sandalwood",
                            Name = "Noir Extreme",
                            Price = 180m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Versace",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "New and exquisite qualities of natural citrus, aquatic notes, and violet leaves combined with modern hints of fig leaf to give an incisive, Mediterranean freshness.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861793/ScentShop/for%20Him/versace-dylan-blue_canfvk.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Fig Leaf, Bergamot, Patchouli",
                            Name = "Dylan Blue",
                            Price = 200m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Versace",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "Diamante Citrus, Bitter Orange leaves and Neiroli flowers light up the fragrance with Mediterranean accents. The heart of Versace Pour Homme is characterized by the mineral-floral aroma, almost tactile, of Clary Sage and Blue Hyacinth. Amber and Musk deliver deep and sensual base notes.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861793/ScentShop/for%20Him/versace-pour-homme_he9rl1.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = true,
                            KeyNotes = "Bergamot, Neroli, Citron of Diamante",
                            Name = "Pour Homme",
                            Price = 200m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Nautica",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The composition opens with cold, green notes of leaves and apple. There is a tender dewy mimose in the heart, which is blended with watery note of lotus and an interesting accord of linen sail of a yacht. The composition is laid on a woody base, combined of cedar, moss, musk and amber.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861792/ScentShop/for%20Him/nautica-voyage_nhtnhw.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Apple, Lotus, Cedar",
                            Name = "Voyage",
                            Price = 300m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Giorgio Armani",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "A light, distinguished fragrance inspired by the fresh sea, warm sun and the richness of the earth. It opens with a splash of fresh calabrian bergamot, neroli and green tangerine. Light, aquatic nuances mix with jasmine petal, crisp rock rose, rosemary, fruity persimmon and warm Indonesian patchouli to create a masculine scent that is both fresh and sensual.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861789/ScentShop/for%20Him/giorgio-armani-acqua_vgzmvl.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Bergamot, Neroli, Green Tangerine",
                            Name = "Acqua di Gio",
                            Price = 150m
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Hugo Boss",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "A radiant and sensual fragrance that opens with juicy white peach for a lively, fizzy character with an enticing sweetness. The modern top is complemented with an ultra-feminine heart comprising classic white florals and violet.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861771/ScentShop/for%20Her/hugo-boss-nuit_elbd6k.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Peach, Jasmine, Almond",
                            Name = "Boss Nuit",
                            Price = 190m
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Amouage",
                            Capacity = 100,
                            CategoryId = 1,
                            Description = "Amouage Gold is the first fragrance of Amouage. The top notes blend wild rose, lily-of-the-valley and silver frankincense. The heart notes include myrrh, orris and jasmine. The oriental base is of ambergris, civet, musk, cedarwood and sandalwood.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861770/ScentShop/for%20Her/amouage-gold-woman_ivbu3k.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Jasmine, Orris Root, Myrrh, Musk",
                            Name = "Amouage Gold",
                            Price = 270m
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Versace",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "Eros is a vibrant, and glowing combination of fresh mint leaves, Italian lemon zest, and green apple. An addictive sensuality accented by oriental, intriguing, and enveloping notes like tonka beans, amrboxan amber, geranium flower, and vanilla melds with a racy virility symbolized by woods — such as cedarwood from Atlas and Virginia.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861794/ScentShop/for%20Him/versace-eros_dgyr6q.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Mint Leaves, Green Apple, Lemon, Orange Blossom",
                            Name = "Eros",
                            Price = 98m
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Hugo Boss",
                            Capacity = 100,
                            CategoryId = 2,
                            Description = "Boss Bottled Night is a fragrance which abounds in intense and masculine woody accords. It opens with lavender and birch tree aromas, while accentuating intense heart aromas of African violet, resting on a base constructed of warm, precious woody nuances of Louro Amarelo tree and sensual musk.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861789/ScentShop/for%20Him/hugo_boss_bottled_night_byvaj7.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Afircan Violet, Amarelo Tree, Musk",
                            Name = "Bottled Night",
                            Price = 155m
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Giorgio Armani",
                            Capacity = 50,
                            CategoryId = 2,
                            Description = "The first oriental Giorgio Armani cologne for men, this aromatic fragrance blends the freshness of bergamot, the soft sensuality of olive flower, and the warmth of guaiac wood and tonka bean.",
                            ImageUrl = "https://res.cloudinary.com/do0ohxztp/image/upload/v1618861772/ScentShop/for%20Her/giorgio-armani-armani-code_mek46g.png",
                            InStock = true,
                            IsPerfumeOfTheWeek = false,
                            KeyNotes = "Olive Tree Blossom, Guaiac Wood, Tonka Bean",
                            Name = "Armani Code",
                            Price = 68m
                        });
                });

            modelBuilder.Entity("ScentShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PerfumeId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScentShop.Models.OrderDetail", b =>
                {
                    b.HasOne("ScentShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScentShop.Models.Perfume", "Perfume")
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("ScentShop.Models.Perfume", b =>
                {
                    b.HasOne("ScentShop.Models.Category", "Category")
                        .WithMany("Perfumes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScentShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("ScentShop.Models.Perfume", "Perfume")
                        .WithMany()
                        .HasForeignKey("PerfumeId");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("ScentShop.Models.Category", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("ScentShop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
